// This is the top module of the single-cycle MIPS processor. It takes clock and reset as inputs
module Single_Cycle_MIPS(clk,rst);
input clk,rst; 
// These are control signals generated by the control unit to control datapath operations.
/*
MemtoReg ? memory or ALU result
MemWrite ? write to memory
Branch ? branch instruction
ALUSrc ? register vs immediate
RegDst ? rd vs rt
*/
reg MemtoReg,MemWrite,Branch,ALUSrc,RegDst,RegWrite,Jump;
wire PCSrc;
// ALUOp gives high-level instruction type, ALUControl gives exact ALU operation.
reg [2:0]ALUControl;
reg [1:0]ALUOp;
// These wires carry data between different blocks in the datapath.
wire [31:0] pci;
wire [31:0]pciwire1,pciwire2,pco,Instr,signImm,SrcA,SrcB,ReadData_Wire,WriteData,PCbranch,Result;
wire [4:0]WriteReg;
wire [5:0]opcode,funct;
// These store ALU result, zero flag, and next PC value
reg Zero;
reg [31:0]ALUResult;
reg [31:0]pcplus4;

// PC outputs current address and updates with next address.
Program_Counter pc(.clk(clk),.rst(rst),.pci(pciwire2),.pco(pco));
// Fetches instruction from memory using PC.
Instruction_mem im(.clk(clk),.rst(rst),.A(pco),.RD(Instr));
//Reads two registers and writes one register.
/*
Important mapping:
Instr[25:21] ? rs
Instr[20:16] ? rt
WriteReg ? destination
*/
Register_File rf(.clk(clk),.rst(rst),.WE3(RegWrite),.A1(Instr[25:21]),.A2(Instr[20:16]),.A3(WriteReg),.WD3(Result),.RD1(SrcA),.RD2(WriteData));
// Used for load and store instructions.
Data_Mem dm(.clk(clk),.rst(rst),.WE(MemWrite),.A(ALUResult),.WD(WriteData),.RD(ReadData_Wire));

assign pci=pciwire2;
// Extends 16-bit immediate to 32-bit signed value.
assign signImm = {Instr[15]}? {16'hffff,Instr[15:0]} : {16'h0000,Instr[15:0]};
// Second ALU operand is selected between register value and immediate.
assign SrcB = ALUSrc ? signImm : WriteData;
// Final data written to register comes from memory or ALU.
assign Result = MemtoReg ? ReadData_Wire : ALUResult;
// Selects destination register: rd for R-type, rt for I-type.
assign WriteReg = RegDst ? Instr[15:11] : Instr[20:16];
// Branch is taken when Zero flag is 1.
assign PCSrc = Branch & Zero;
assign PCbranch = (signImm<<2) + pcplus4;
//Next PC is chosen between sequential, branch, or jump address.
assign pciwire1 = PCSrc? PCbranch : pcplus4;
assign pciwire2 = Jump ? {pcplus4[31:28],Instr[25:0]<<2} : pciwire1;
// Opcode identifies instruction type, funct identifies ALU operation in R-type.
assign opcode = Instr[31:26];
assign funct = Instr[5:0];
// Control Unit
//This block generates control signals based on instruction opcode.
always @(*) begin
    casex (opcode)
        6'b000000: begin
            RegWrite = 1'b1;
            RegDst = 1'b1;
            ALUSrc = 1'b0;
            Branch = 1'b0;
            MemWrite = 1'b0;
            MemtoReg = 1'b0;
            ALUOp = 2'b10;
            Jump = 1'b0;
        end
        6'b100011: begin
            RegWrite = 1'b1;
            RegDst = 1'b0;
            ALUSrc = 1'b1;
            Branch = 1'b0;
            MemWrite = 1'b0;
            MemtoReg = 1'b1;
            ALUOp = 2'b00;
            Jump = 1'b0;
        end
        6'b101011: begin
            RegWrite = 1'b0;
            RegDst = 1'bx;
            ALUSrc = 1'b1;
            Branch = 1'b0;
            MemWrite = 1'b1;
            MemtoReg = 1'bx;
            ALUOp = 2'b00;
            Jump = 1'b0;
        end
        6'b000100: begin
            RegWrite = 1'b0;
            RegDst = 1'bx;
            ALUSrc = 1'b0;
            Branch = 1'b1;
            MemWrite = 1'b0;
            MemtoReg = 1'bx;
            ALUOp = 2'b01;
            Jump = 1'b0;
        end
        6'b001000: begin
            RegWrite = 1'b1;
            RegDst = 1'b0;
            ALUSrc = 1'b1;
            Branch = 1'b0;
            MemWrite = 1'b0;
            MemtoReg = 1'b0;
            ALUOp = 2'b00;
            Jump = 1'b0;
        end
        6'b000010: begin
            RegWrite = 1'b0;
            RegDst = 1'bx;
            ALUSrc = 1'bx;
            Branch = 1'bx;
            MemWrite = 1'b0;
            MemtoReg = 1'bx;
            ALUOp = 2'bxx;
            Jump = 1'b1;
        end
        default: begin
            RegWrite = 1'b0;
            RegDst = 1'b0;
            ALUSrc = 1'b0;
            Branch = 1'b0;
            MemWrite = 1'b0;
            MemtoReg = 1'b0;
            ALUOp = 2'b00;
            Jump = 1'b0;
        end 
    endcase
end

// Generates ALUControl signal based on ALUOp and funct.
/*
Key:
00 ? ADD
01 ? SUB
10 ? use funct
*/
always @(*) begin
    casex (ALUOp)
        2'b00:ALUControl = 3'b010;
        2'bx1:ALUControl = 3'b110;
        2'b1x:case(funct)
            6'b100000: ALUControl = 3'b010;
            6'b100010: ALUControl = 3'b110;
            6'b100100: ALUControl = 3'b000;
            6'b100101: ALUControl = 3'b001;
            6'b101010: ALUControl = 3'b111;
            default: ALUControl = 3'b010;
        endcase
        default: ALUControl = 3'b010;
    endcase
end
//Performs arithmetic and logical operations.
/*
Operations:
AND ? &
OR ? |
ADD ? +
SUB ? -
SLT ? comparison
*/
always @(*) begin
    case (ALUControl)
        3'b000: ALUResult = SrcA & SrcB;
        3'b001: ALUResult = SrcA | SrcB;
        3'b010: ALUResult = SrcA + SrcB;
        3'b100: ALUResult = SrcA &~SrcB;
        3'b101: ALUResult = SrcA |~SrcB;
        3'b110: ALUResult = SrcA - SrcB;
        3'b111: ALUResult = (SrcA < SrcB) ? 32'h1 : 32'h0;
        default: ALUResult = 32'h0;
    endcase
    // Zero flag is used for branch decision.
    if(ALUResult == 32'h0)
        Zero = 1'b1;
    else
        Zero = 1'b0;
end
always @(*) begin
    // Next sequential instruction address
    pcplus4=pco+32'h4;
end
endmodule

/*
Note:
Since it is single-cycle, all instructions complete in one clock, so the clock period is decided by the slowest instruction.
Working: PC gives address ? instruction fetched ? registers read ? ALU performs operation ? memory accessed if needed ? result written back ? next PC calculated using branch/jump logic.
*/
